/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import Model.ChatLieu;
import Model.MauSac;
import Model.PhanLoai;
import Model.SanPham;
import Model.SanPhamChiTiet;
import Model.ThuongHieu;
import Model.XuatXu;
import Service.ChatLieuService;
import Service.MauSacService;
import Service.PhanLoaiService;
import Service.SPCTService;
import Service.SanPhamService;
import Service.ThuongHieuService;
import Service.XuatXuService;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class QLSPCTForm extends javax.swing.JPanel {

    private DefaultTableModel dtm = new DefaultTableModel();
    private SanPhamService spservice = new SanPhamService();
    private SPCTService service = new SPCTService();
    private ChatLieuService cls = new ChatLieuService();
    private PhanLoaiService pls = new PhanLoaiService();
    private MauSacService mss = new MauSacService();
    private ThuongHieuService ths = new ThuongHieuService();
    private XuatXuService xxs = new XuatXuService();
    private static SanPham sp;

    /**
     * Creates new form QLSPCTForm
     */
    public QLSPCTForm() {
        initComponents();
        LoadCBO();
        fillTable(service.gettAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnthemphanloai = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtkhoiluong = new javax.swing.JTextField();
        txtkichthuoc = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbochatlieu = new javax.swing.JComboBox<>();
        btnthemth = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        btnsua = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblspanh = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblspct = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtamota = new javax.swing.JTextArea();
        txtgia = new javax.swing.JTextField();
        cboxuatxu = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbothuonghieu = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnthemxx = new javax.swing.JButton();
        cbomausac = new javax.swing.JComboBox<>();
        tbmthemms = new javax.swing.JButton();
        cbophanloai = new javax.swing.JComboBox<>();
        btnthemcl = new javax.swing.JButton();
        txtid = new javax.swing.JLabel();

        btnthemphanloai.setText("+");
        btnthemphanloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemphanloaiActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Xuất xứ:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Kích thước:");

        txtkhoiluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtkichthuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Thương hiệu:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Chất liệu:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Phân loại:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Màu sắc:");

        cbochatlieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbochatlieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnthemth.setText("+");
        btnthemth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemthActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID sản phẩm:");

        txtsoluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Sản phẩm chi tiết");

        lblspanh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Mô tả:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Giá:");

        tblspct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblspct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Phân loại", "Chất liệu", "Thương hiệu", "Màu sắc", "Xuất xứ", "Kích thước", "Khối lượng", "Số lượng", "Giá", "Mô tả", "Ảnh"
            }
        ));
        tblspct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblspctMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblspct);

        txtamota.setColumns(20);
        txtamota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtamota.setRows(5);
        jScrollPane1.setViewportView(txtamota);

        txtgia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cboxuatxu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxuatxu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Số lượng:");

        cbothuonghieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbothuonghieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Khối lượng:");

        btnthemxx.setText("+");
        btnthemxx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemxxActionPerformed(evt);
            }
        });

        cbomausac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbomausac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbmthemms.setText("+");
        tbmthemms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbmthemmsActionPerformed(evt);
            }
        });

        cbophanloai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbophanloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnthemcl.setText("+");
        btnthemcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemclActionPerformed(evt);
            }
        });

        txtid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtid.setText("23924-329232-92349-1239");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnsua)
                        .addGap(35, 35, 35)
                        .addComponent(btnxoa))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblspanh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtkichthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(31, 31, 31)
                                                .addComponent(txtkhoiluong, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(272, 272, 272)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel13)
                                        .addComponent(jLabel14))))
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbochatlieu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbophanloai, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbomausac, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbothuonghieu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cboxuatxu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnthemcl)
                                .addComponent(btnthemxx)
                                .addComponent(btnthemth)
                                .addComponent(tbmthemms)
                                .addComponent(btnthemphanloai))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(txtgia, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(txtsoluong)))))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(451, 451, 451))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnthemcl, btnthemphanloai, btnthemth, btnthemxx, tbmthemms});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtid)
                                    .addComponent(jLabel12)
                                    .addComponent(cbochatlieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnthemcl)
                                    .addComponent(jLabel7)
                                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnthemphanloai, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel11)
                                        .addComponent(cbophanloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel6)
                                        .addComponent(txtkhoiluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(cbomausac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tbmthemms, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(txtkichthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(cbothuonghieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnthemth, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(btnthemxx, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboxuatxu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 51, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblspanh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxoa)
                    .addComponent(btnsua))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemphanloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemphanloaiActionPerformed
        PhanLoaiFrame p = new PhanLoaiFrame();
        p.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                LoadCBO();
            }

            @Override
            public void windowClosed(WindowEvent e) {
                LoadCBO();
            }
        });
        p.setVisible(true);
    }//GEN-LAST:event_btnthemphanloaiActionPerformed

    private void btnthemthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemthActionPerformed
        ThuongHieuFrame th = new ThuongHieuFrame();
        th.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                LoadCBO();
            }

            @Override
            public void windowClosed(WindowEvent e) {
                LoadCBO();
            }
        });
        th.setVisible(true);
    }//GEN-LAST:event_btnthemthActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        if (Check()) {
            if (service.SuaSPCT(readFormSPCT()) > 0) {
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                fillTable(service.gettAll());
            }
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void tblspctMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblspctMouseClicked
        // TODO add your handling code here:
        int i = tblspct.getSelectedRow();
        Show(i);
    }//GEN-LAST:event_tblspctMouseClicked

    private void btnthemxxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemxxActionPerformed
        XuatXuFrame x = new XuatXuFrame();
        x.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                LoadCBO();
            }

            @Override
            public void windowClosed(WindowEvent e) {
                LoadCBO();
            }
        });
        x.setVisible(true);
    }//GEN-LAST:event_btnthemxxActionPerformed

    private void tbmthemmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbmthemmsActionPerformed
        MauSacFrame m = new MauSacFrame();
        m.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                LoadCBO();
            }

            @Override
            public void windowClosed(WindowEvent e) {
                LoadCBO();
            }
        });
        m.setVisible(true);
    }//GEN-LAST:event_tbmthemmsActionPerformed

    private void btnthemclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemclActionPerformed
        ChatLieuFrame c = new ChatLieuFrame();
        c.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                LoadCBO();
            }

            @Override
            public void windowClosed(WindowEvent e) {
                LoadCBO();
            }
        });
        c.setVisible(true);
    }//GEN-LAST:event_btnthemclActionPerformed

    private void fillTable(List<SanPhamChiTiet> l) {
        dtm = (DefaultTableModel) tblspct.getModel();
        dtm.setRowCount(0);
        for (SanPhamChiTiet x : l) {
            dtm.addRow(new Object[]{
                x.getId(), pls.findPL(x.getIdpl()).getTen(), cls.findCL(x.getIdcl()).getTen(), ths.findTH(x.getIdth()).getTen(), mss.findMS(x.getIdms()).getTen(),
                xxs.findXX(x.getIdxx()).getTen(), x.getKichThuoc(), x.getKhoiLuong(), x.getSoLuong(), x.getGia(), x.getMoTa(), x.getAnh()
            });
        }
    }

    private void LoadCBO() {
        cbochatlieu.removeAllItems();
        cbomausac.removeAllItems();
        cbophanloai.removeAllItems();
        cbothuonghieu.removeAllItems();
        cboxuatxu.removeAllItems();
        for (ChatLieu x : cls.gettAll()) {
            cbochatlieu.addItem(x.getTen());
        }
        for (PhanLoai x : pls.gettAll()) {
            cbophanloai.addItem(x.getTen());
        }
        for (MauSac x : mss.gettAll()) {
            cbomausac.addItem(x.getTen());
        }
        for (ThuongHieu x : ths.gettAll()) {
            cbothuonghieu.addItem(x.getTen());
        }
        for (XuatXu x : xxs.gettAll()) {
            cboxuatxu.addItem(x.getTen());
        }
    }

    private void Show(int i) {
        txtid.setText(tblspct.getValueAt(i, 0).toString());
        cbophanloai.setSelectedItem(tblspct.getValueAt(i, 1).toString());
        cbochatlieu.setSelectedItem(tblspct.getValueAt(i, 2).toString());
        cbothuonghieu.setSelectedItem(tblspct.getValueAt(i, 3).toString());
        cbomausac.setSelectedItem(tblspct.getValueAt(i, 4).toString());
        cboxuatxu.setSelectedItem(tblspct.getValueAt(i, 5).toString());
        txtkichthuoc.setText(tblspct.getValueAt(i, 6).toString());
        txtkhoiluong.setText(tblspct.getValueAt(i, 7).toString());
        txtsoluong.setText(tblspct.getValueAt(i, 8).toString());
        txtgia.setText(tblspct.getValueAt(i, 9).toString());
        txtamota.setText(tblspct.getValueAt(i, 10).toString());
    }

    public SanPhamChiTiet readFormSPCT() {
        SanPhamChiTiet spct = new SanPhamChiTiet();
        spct.setIdpl(pls.findidPL(cbophanloai.getSelectedItem().toString()).getId());
        spct.setIdms(mss.findidMS(cbomausac.getSelectedItem().toString()).getId());
        spct.setIdcl(cls.findidCL(cbochatlieu.getSelectedItem().toString()).getId());
        spct.setIdth(ths.findidTH(cbothuonghieu.getSelectedItem().toString()).getId());
        spct.setIdxx(xxs.findidXX(cboxuatxu.getSelectedItem().toString()).getId());
        spct.setKichThuoc(txtkichthuoc.getText());
        spct.setKhoiLuong(Float.valueOf(txtkhoiluong.getText()));
        spct.setSoLuong(Integer.parseInt(txtsoluong.getText()));
        spct.setGia(Float.parseFloat(txtgia.getText()));
        spct.setMoTa(txtamota.getText());
        return spct;
    }

    public void Clear() {
        txtamota.setText("");
        txtgia.setText("");
        txtsoluong.setText("");
        txtkhoiluong.setText("");
        txtkichthuoc.setText("");
        cbochatlieu.setSelectedIndex(0);
        cbomausac.setSelectedIndex(0);
        cbophanloai.setSelectedIndex(0);
        cbothuonghieu.setSelectedIndex(0);
        cboxuatxu.setSelectedIndex(0);
    }

    public boolean Check() {
        Boolean c = true;
        try {
            Integer.parseInt(txtsoluong.getText());
            c = true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số nguyên");
            c = false;
        }
        try {
            Double.parseDouble(txtkhoiluong.getText());
            c = true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số");
            c = false;
        }
        try {
            Double.parseDouble(txtgia.getText());
            c = true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá tiền phải là số");
            c = false;
        }
        if (txtkhoiluong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Khối lượng không trống");
            c = false;
        } else {
            if (Float.parseFloat(txtkhoiluong.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "Khối lượng phải lớn hơn 0");
                c = false;
            }
        }
        if (txtkichthuoc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kích thước không trống");
            c = false;
        }
        if (txtsoluong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số lượng không trống");
            c = false;
        } else {
            if (Integer.parseInt(txtsoluong.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0");
                c = false;
            }
        }
        if (txtgia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Giá tiền không trống");
            c = false;
        } else {
            if (Integer.parseInt(txtsoluong.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "Giá tiền phải lớn hơn 0");
                c = false;
            }
        }
        return c;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthemcl;
    private javax.swing.JButton btnthemphanloai;
    private javax.swing.JButton btnthemth;
    private javax.swing.JButton btnthemxx;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbochatlieu;
    private javax.swing.JComboBox<String> cbomausac;
    private javax.swing.JComboBox<String> cbophanloai;
    private javax.swing.JComboBox<String> cbothuonghieu;
    private javax.swing.JComboBox<String> cboxuatxu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblspanh;
    private javax.swing.JTable tblspct;
    private javax.swing.JButton tbmthemms;
    private javax.swing.JTextArea txtamota;
    private javax.swing.JTextField txtgia;
    private javax.swing.JLabel txtid;
    private javax.swing.JTextField txtkhoiluong;
    private javax.swing.JTextField txtkichthuoc;
    private javax.swing.JTextField txtsoluong;
    // End of variables declaration//GEN-END:variables
}
