/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import Model.SanPham;
import Service.SanPhamService;
import com.raven.main.Main;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class QLSPForm extends javax.swing.JPanel {

    private DefaultTableModel dtm = new DefaultTableModel();
    private SanPhamService spservice = new SanPhamService();
    private int isp = -1;
    private MainForm mainf;
    private Main main;
    private int pageNumber = 1;
    private int pageSize = 6;
    private int curentPage = 1;

    /**
     * Creates new form QLSPForm
     */
    public QLSPForm() {
        initComponents();
//        fillTBLSanPham(spservice.gettAll());
        fillTBLSanPham(spservice.gettAllPT(pageNumber, pageSize));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        btnnextsp = new javax.swing.JButton();
        btnpresp = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsanpham = new javax.swing.JTable();
        txttimsp = new javax.swing.JTextField();
        lblidsp = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnmoisp = new javax.swing.JButton();
        btnthemsp = new javax.swing.JButton();
        txtmasp = new javax.swing.JTextField();
        txttensp = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tbnxoasp = new javax.swing.JButton();
        btnsuasp = new javax.swing.JButton();
        btnchitietsp = new javax.swing.JButton();
        lblcurrent = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Quản lý sản phẩm");

        btnnextsp.setText(">");
        btnnextsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextspActionPerformed(evt);
            }
        });

        btnpresp.setText("<");
        btnpresp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprespActionPerformed(evt);
            }
        });

        tblsanpham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblsanpham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Sản phẩm", "Mã sản phẩm", "Tên sản phẩm"
            }
        ));
        tblsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsanphamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblsanpham);

        txttimsp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txttimsp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimspKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttimspKeyTyped(evt);
            }
        });

        lblidsp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblidsp.setText("S0281931");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("ID sản phẩm:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Tìm kiếm:");

        btnmoisp.setText("Mới");
        btnmoisp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoispActionPerformed(evt);
            }
        });

        btnthemsp.setText("Thêm");
        btnthemsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemspActionPerformed(evt);
            }
        });

        txtmasp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txttensp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Tên sản phẩm:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Mã sản phẩm:");

        tbnxoasp.setText("Ẩn");
        tbnxoasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnxoaspActionPerformed(evt);
            }
        });

        btnsuasp.setText("Sửa");
        btnsuasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaspActionPerformed(evt);
            }
        });

        btnchitietsp.setText("Chi tiết");
        btnchitietsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchitietspActionPerformed(evt);
            }
        });

        lblcurrent.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel12)
                                        .addComponent(jLabel7)))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtmasp, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblidsp, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(49, 49, 49)
                                .addComponent(txttimsp, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnpresp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(lblcurrent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnnextsp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 472, Short.MAX_VALUE)
                                .addComponent(btnmoisp, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnthemsp, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnsuasp)
                                .addGap(18, 18, 18)
                                .addComponent(btnchitietsp)
                                .addGap(18, 18, 18)
                                .addComponent(tbnxoasp))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(442, 442, 442)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnchitietsp, btnmoisp, btnsuasp, btnthemsp, tbnxoasp});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnnextsp, btnpresp});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel6)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblidsp))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtmasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txttensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnpresp)
                            .addComponent(lblcurrent)
                            .addComponent(btnnextsp)
                            .addComponent(btnthemsp)
                            .addComponent(btnmoisp)
                            .addComponent(btnsuasp)
                            .addComponent(tbnxoasp)
                            .addComponent(btnchitietsp))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txttimsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(271, 271, 271))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblsanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsanphamMouseClicked
        // TODO add your handling code here:
        isp = tblsanpham.getSelectedRow();
        ShowSP(isp);
    }//GEN-LAST:event_tblsanphamMouseClicked

    private void btnchitietspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchitietspActionPerformed
        
        isp = tblsanpham.getSelectedRow();
        viewSPCT spct = new viewSPCT(spservice.findSPByID(tblsanpham.getValueAt(isp, 0).toString()));
        spct.setVisible(true);
    }//GEN-LAST:event_btnchitietspActionPerformed

    private void tbnxoaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnxoaspActionPerformed
        // TODO add your handling code here:
        isp = tblsanpham.getSelectedRow();

        int c = JOptionPane.showConfirmDialog(this, "Sản phẩm được chọn sẽ được chuyển vào danh sách xóa", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (c == 0) {
            if (spservice.AnSP(tblsanpham.getValueAt(isp, 0).toString()) > 0) {
                JOptionPane.showMessageDialog(this, "Thành công");
                fillTBLSanPham(spservice.gettAllPT(curentPage, pageSize));
            } else {
                JOptionPane.showMessageDialog(this, "Thất bại");
            }
        }
    }//GEN-LAST:event_tbnxoaspActionPerformed

    private void btnthemspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemspActionPerformed
        // TODO add your handling code here:
        if (CheckSP()) {
            if (spservice.AddSP(readFormSP()) > 0) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                fillTBLSanPham(spservice.gettAllPT(curentPage, pageSize));
                viewSPCT spct = new viewSPCT(spservice.findSPByMa(txtmasp.getText()));
                spct.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        }

    }//GEN-LAST:event_btnthemspActionPerformed

    private void btnsuaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaspActionPerformed
        // TODO add your handling code here:
        if (CheckSPT()) {
            if (spservice.UpdateSP(readFormSP()) > 0) {
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                fillTBLSanPham(spservice.gettAllPT(curentPage, pageSize));
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thất bại");
            }
        }
    }//GEN-LAST:event_btnsuaspActionPerformed

    private void btnmoispActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoispActionPerformed
        // TODO add your handling code here:
        Clearsp();
    }//GEN-LAST:event_btnmoispActionPerformed

    private void btnnextspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextspActionPerformed
        // TODO add your handling code here:

        if (spservice.gettAllPT(curentPage, pageSize).isEmpty()) {
            JOptionPane.showMessageDialog(this, "Hết");
        } else {
            curentPage++;
            fillTBLSanPham(spservice.gettAllPT(curentPage, pageSize));
            lblcurrent.setText(String.valueOf(curentPage));
        }
    }//GEN-LAST:event_btnnextspActionPerformed

    private void btnprespActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprespActionPerformed
        // TODO add your handling code here:
        if (curentPage > 1) {
            curentPage--;
            fillTBLSanPham(spservice.gettAllPT(curentPage, pageSize));
        }
        lblcurrent.setText(String.valueOf(curentPage));
    }//GEN-LAST:event_btnprespActionPerformed

    private void txttimspKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimspKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txttimspKeyReleased

    private void txttimspKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimspKeyTyped
        // TODO add your handling code here:
        String t = txttimsp.getText();
        if (t.isEmpty()) {
            fillTBLSanPham(spservice.gettAllPT(curentPage, pageSize));
        } else {
            fillTBLSanPham(spservice.findAll(t, curentPage, pageSize));
        }
    }//GEN-LAST:event_txttimspKeyTyped

    private void fillTBLSanPham(List<SanPham> l) {
        dtm = (DefaultTableModel) tblsanpham.getModel();
        dtm.setRowCount(0);
        for (SanPham x : l) {
            dtm.addRow(new Object[]{
                x.getId(), x.getMaSP(), x.getTenSP()
            });
        }
    }

    private void ShowSP(int i) {

        lblidsp.setText(tblsanpham.getValueAt(i, 0).toString());
        txtmasp.setText(tblsanpham.getValueAt(i, 1).toString());
        txttensp.setText(tblsanpham.getValueAt(i, 2).toString());
    }

    private SanPham readFormSP() {
        SanPham sp = new SanPham();
        sp.setId(lblidsp.getText());
        sp.setMaSP(txtmasp.getText().trim());
        sp.setTenSP(txttensp.getText().trim());
        return sp;
    }

    private void Clearsp() {
        isp = -1;
        lblidsp.setText("");
        txttensp.setText("");
        txtmasp.setText("");
    }

    public boolean CheckSP() {
        boolean check = true;
        if (txtmasp.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã sản phẩm không được trống");
            check = false;
        }
        for (SanPham x : spservice.gettAll()) {
            if (x.getMaSP().equals(txtmasp.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Mã sản phẩm đã tồn tại");
                check = false;
            }
        }
        if (txttensp.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên sản phẩm không được trống");
            check = false;
        }
        for (SanPham x : spservice.gettAll()) {
            if (x.getTenSP().equals(txttensp.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Đã có sản phẩm cùng tên");
                check = false;
            }
        }
        return check;
    }
    public boolean CheckSPT() {
        boolean check = true;
        if (txtmasp.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Mã sản phẩm không được trống");
            check = false;
        }
        for (SanPham x : spservice.gettAll()) {
            int i = 0;
            if (x.getMaSP().equals(txtmasp.getText().trim())) {
                i++;
            }
            if(i>0){
                JOptionPane.showMessageDialog(this, "Mã sản phẩm đã tồn tại");
                check = false;
            }
        }
        if (txttensp.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên sản phẩm không được trống");
            check = false;
        }

        return check;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnchitietsp;
    private javax.swing.JButton btnmoisp;
    private javax.swing.JButton btnnextsp;
    private javax.swing.JButton btnpresp;
    private javax.swing.JButton btnsuasp;
    private javax.swing.JButton btnthemsp;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcurrent;
    private javax.swing.JLabel lblidsp;
    private javax.swing.JTable tblsanpham;
    private javax.swing.JButton tbnxoasp;
    private javax.swing.JTextField txtmasp;
    private javax.swing.JTextField txttensp;
    private javax.swing.JTextField txttimsp;
    // End of variables declaration//GEN-END:variables
}
