/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.raven.form;

import Model.ChatLieu;
import Model.MauSac;
import Model.PhanLoai;
import Model.SanPham;
import Model.SanPhamChiTiet;
import Model.SanPham_SPCT;
import Model.ThuongHieu;
import Model.XuatXu;
import Service.ChatLieuService;
import Service.MauSacService;
import Service.PhanLoaiService;
import Service.SPCTService;
import Service.SanPhamService;
import Service.ThuongHieuService;
import Service.XuatXuService;
import Utils.DBContext;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class viewSPCT extends javax.swing.JFrame {

    private DefaultTableModel dtm = new DefaultTableModel();
    private SanPhamService spservice = new SanPhamService();
    private SPCTService service = new SPCTService();
    private ChatLieuService cls = new ChatLieuService();
    private PhanLoaiService pls = new PhanLoaiService();
    private MauSacService mss = new MauSacService();
    private ThuongHieuService ths = new ThuongHieuService();
    private XuatXuService xxs = new XuatXuService();
    private static SanPham sp;
    private Connection con = DBContext.getConnection();

    /**
     * Creates new form viewSPCT
     *
     * @param id
     */
    public viewSPCT(SanPham sp) {
        initComponents();
        LoadCBO();
        setLocationRelativeTo(null);
        lblmasp.setText(sp.getMaSP());
        lbltensp.setText(sp.getTenSP());
        abc.setText(sp.getId());
        abc.setVisible(false);
        fillTable(service.findSPCTByIDSP(abc.getText()));
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        btnxoa.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnthemxx = new javax.swing.JButton();
        cbomausac = new javax.swing.JComboBox<>();
        tbmthemms = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbophanloai = new javax.swing.JComboBox<>();
        txtsoluong = new javax.swing.JTextField();
        btnthemcl = new javax.swing.JButton();
        lbltensp = new javax.swing.JLabel();
        txtid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblmasp = new javax.swing.JLabel();
        lblspanh = new javax.swing.JLabel();
        btnthemphanloai = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtkhoiluong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblspct = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtkichthuoc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtamota = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtgia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cboxuatxu = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbothuonghieu = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbochatlieu = new javax.swing.JComboBox<>();
        btnthemth = new javax.swing.JButton();
        btnmoi = new javax.swing.JButton();
        btnthem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txttimma = new javax.swing.JTextField();
        cbogia = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        cbophanloai1 = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        cbothuonghieu1 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        cbomausac1 = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        cboxuatxu1 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        cbochatlieu1 = new javax.swing.JComboBox<>();
        btnxemct = new javax.swing.JButton();
        abc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnthemxx.setText("+");
        btnthemxx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemxxActionPerformed(evt);
            }
        });

        cbomausac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbomausac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tbmthemms.setText("+");
        tbmthemms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbmthemmsActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("ID sản phẩm:");

        cbophanloai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbophanloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtsoluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnthemcl.setText("+");
        btnthemcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemclActionPerformed(evt);
            }
        });

        lbltensp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbltensp.setText("MaSP");

        txtid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtid.setText("23924-329232-92349-1239");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Sản phẩm chi tiết");

        lblmasp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblmasp.setText("MaSP");

        lblspanh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnthemphanloai.setText("+");
        btnthemphanloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemphanloaiActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Xuất xứ:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Mô tả:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Kích thước:");

        txtkhoiluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Giá:");

        tblspct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblspct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã sản phẩm", "Tên sản phẩm", "Phân loại", "Chất liệu", "Thương hiệu", "Màu sắc", "Xuất xứ", "Kích thước", "Khối lượng", "Số lượng", "Giá", "Mô tả", "Ảnh"
            }
        ));
        tblspct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblspctMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblspct);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Mã sản phẩm:");

        txtkichthuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtamota.setColumns(20);
        txtamota.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtamota.setRows(5);
        jScrollPane1.setViewportView(txtamota);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tên sản phẩm:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Thương hiệu:");

        txtgia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Chất liệu:");

        cboxuatxu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboxuatxu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Phân loại:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Số lượng:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Màu sắc:");

        cbothuonghieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbothuonghieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Khối lượng:");

        cbochatlieu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbochatlieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnthemth.setText("+");
        btnthemth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemthActionPerformed(evt);
            }
        });

        btnmoi.setText("Mới");
        btnmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoiActionPerformed(evt);
            }
        });

        btnthem.setText("Thêm");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("Ẩn");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        jLabel15.setText("Mã/Tên SP:");

        txttimma.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttimmaKeyReleased(evt);
            }
        });

        cbogia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Thấp hơn 100k", "100k - 200k", "200k - 500k", "Lớn hơn 500k" }));
        cbogia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbogiaActionPerformed(evt);
            }
        });

        jLabel16.setText("Lọc theo giá tiền");

        jLabel18.setText("Lọc theo phân loại");

        cbophanloai1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbophanloai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbophanloai1ActionPerformed(evt);
            }
        });

        jLabel19.setText("Lọc theo chất liệu");

        cbothuonghieu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbothuonghieu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbothuonghieu1ActionPerformed(evt);
            }
        });

        jLabel20.setText("Lọc theo màu sắc");

        cbomausac1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbomausac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbomausac1ActionPerformed(evt);
            }
        });

        jLabel21.setText("Lọc theo xuất xứ");

        cboxuatxu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboxuatxu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxuatxu1ActionPerformed(evt);
            }
        });

        jLabel22.setText("Lọc theo thương hiệu");

        cbochatlieu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbochatlieu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbochatlieu1ActionPerformed(evt);
            }
        });

        btnxemct.setText("Chi tiết sản phẩm hiện tại");
        btnxemct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxemctActionPerformed(evt);
            }
        });

        abc.setText("jLabel17");
        abc.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(445, 445, 445))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnmoi)
                            .addGap(35, 35, 35)
                            .addComponent(btnthem)
                            .addGap(32, 32, 32)
                            .addComponent(btnsua)
                            .addGap(35, 35, 35)
                            .addComponent(btnxoa))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblspanh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel18)
                                                    .addComponent(cbophanloai1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(cbothuonghieu1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel19))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel22))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(cbochatlieu1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel20))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(cbomausac1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jLabel21))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addComponent(cboxuatxu1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(9, 9, 9))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel4)
                                                            .addComponent(jLabel6)
                                                            .addComponent(jLabel5)
                                                            .addComponent(jLabel2))
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(txtid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(lblmasp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(txtkichthuoc, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                                                    .addComponent(txtkhoiluong))
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(layout.createSequentialGroup()
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(jLabel14))
                                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(jLabel13)))))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(cboxuatxu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cbophanloai, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cbochatlieu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cbomausac, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cbothuonghieu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lbltensp, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(20, 20, 20)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel11)
                                                            .addComponent(jLabel10)
                                                            .addComponent(jLabel12))
                                                        .addGap(172, 172, 172)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnthemcl)
                                                    .addComponent(btnthemphanloai)
                                                    .addComponent(tbmthemms)
                                                    .addComponent(btnthemth)
                                                    .addComponent(btnthemxx)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txttimma, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtsoluong, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                                            .addComponent(txtgia)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbogia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnxemct))))))
                    .addComponent(abc, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnthemcl, btnthemphanloai, btnthemth, btnthemxx, tbmthemms});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(abc)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblspanh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbochatlieu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboxuatxu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbomausac1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbothuonghieu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbophanloai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttimma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtid)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel12)
                                    .addComponent(cbochatlieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnthemcl))
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(lblmasp, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(cbophanloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnthemphanloai))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(lbltensp, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10)
                                            .addComponent(cbomausac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9)
                                            .addComponent(tbmthemms, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(txtkhoiluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13)
                                            .addComponent(cbothuonghieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnthemth, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(txtkichthuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14)
                                            .addComponent(cboxuatxu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnthemxx, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbogia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnxemct))))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmoi)
                    .addComponent(btnthem)
                    .addComponent(btnxoa)
                    .addComponent(btnsua))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthemxxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemxxActionPerformed
        XuatXuFrame x = new XuatXuFrame();

        x.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                LoadCBO();fillTable(service.findSPCTByIDSP(abc.getText()));
            }

            @Override
            public void windowClosed(WindowEvent e) {
                LoadCBO();fillTable(service.findSPCTByIDSP(abc.getText()));
            }
        });
        x.setVisible(true);
    }//GEN-LAST:event_btnthemxxActionPerformed

    private void tbmthemmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbmthemmsActionPerformed
        MauSacFrame m = new MauSacFrame();
        m.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                LoadCBO();fillTable(service.findSPCTByIDSP(abc.getText()));
            }

            @Override
            public void windowClosed(WindowEvent e) {
                LoadCBO();fillTable(service.findSPCTByIDSP(abc.getText()));
            }
        });
        m.setVisible(true);
    }//GEN-LAST:event_tbmthemmsActionPerformed

    private void btnthemclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemclActionPerformed
        ChatLieuFrame c = new ChatLieuFrame();
        c.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                LoadCBO();
                fillTable(service.findSPCTByIDSP(abc.getText()));
            }

            @Override
            public void windowClosed(WindowEvent e) {
                LoadCBO();
                fillTable(service.findSPCTByIDSP(abc.getText()));
            }
        });
        c.setVisible(true);
        
    }//GEN-LAST:event_btnthemclActionPerformed

    private void btnthemphanloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemphanloaiActionPerformed
        PhanLoaiFrame p = new PhanLoaiFrame();
        p.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                LoadCBO();fillTable(service.findSPCTByIDSP(abc.getText()));
            }

            @Override
            public void windowClosed(WindowEvent e) {
                LoadCBO();fillTable(service.findSPCTByIDSP(abc.getText()));
            }
        });
        p.setVisible(true);

    }//GEN-LAST:event_btnthemphanloaiActionPerformed

    private void tblspctMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblspctMouseClicked
        // TODO add your handling code here:
        int i = tblspct.getSelectedRow();
        Show(i);
    }//GEN-LAST:event_tblspctMouseClicked

    private void btnthemthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemthActionPerformed
        ThuongHieuFrame th = new ThuongHieuFrame();
        th.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                LoadCBO();fillTable(service.findSPCTByIDSP(abc.getText()));
            }

            @Override
            public void windowClosed(WindowEvent e) {
                LoadCBO();fillTable(service.findSPCTByIDSP(abc.getText()));
            }
        });
        th.setVisible(true);
    }//GEN-LAST:event_btnthemthActionPerformed

    private void btnmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoiActionPerformed
        // TODO add your handling code here:
        Clear();
    }//GEN-LAST:event_btnmoiActionPerformed

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if (Check()) {
            if (service.ThemSPCT(readFormSPCT()) > 0) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
                fillTable(service.findSPCTByIDSP(abc.getText()));
            } else {
                JOptionPane.showMessageDialog(this, "Thêm thất bại");
            }
        }
    }//GEN-LAST:event_btnthemActionPerformed

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        if (CheckT()) {
            if (service.SuaSPCT(readFormSPCT()) > 0) {
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                fillTable(service.findSPCTByIDSP(abc.getText()));
            }
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
//        int i = tblspct.getSelectedRow();
//        int chon = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn ẩn?", "Xác nhận ẩn", JOptionPane.YES_NO_OPTION);
//        if (chon == 0) {
//            if (service.AnSPCT(tblspct.getValueAt(i, 0).toString()) > 0) {
//                JOptionPane.showMessageDialog(this, "Ẩn thành công");
//                fillTable(service.findSPCTByIDSP(abc.getText()));
//            } else {
//                JOptionPane.showMessageDialog(this, "Ẩn thất bại");
//            }
//        }

    }//GEN-LAST:event_btnxoaActionPerformed

    private void txttimmaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttimmaKeyReleased
        TimKiemSP();
    }//GEN-LAST:event_txttimmaKeyReleased

    private void cbogiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbogiaActionPerformed
        TimKiemSP();
    }//GEN-LAST:event_cbogiaActionPerformed

    private void cbophanloai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbophanloai1ActionPerformed
        TimKiemSP();
    }//GEN-LAST:event_cbophanloai1ActionPerformed

    private void cbothuonghieu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbothuonghieu1ActionPerformed
        TimKiemSP();
    }//GEN-LAST:event_cbothuonghieu1ActionPerformed

    private void cbomausac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbomausac1ActionPerformed
        TimKiemSP();
    }//GEN-LAST:event_cbomausac1ActionPerformed

    private void cboxuatxu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxuatxu1ActionPerformed
        TimKiemSP();
    }//GEN-LAST:event_cboxuatxu1ActionPerformed

    private void cbochatlieu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbochatlieu1ActionPerformed
        TimKiemSP();
    }//GEN-LAST:event_cbochatlieu1ActionPerformed

    private void btnxemctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxemctActionPerformed
        // TODO add your handling code here:
        fillTable(service.findSPCTByIDSP(abc.getText()));
        
    }//GEN-LAST:event_btnxemctActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewSPCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewSPCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewSPCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewSPCT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SanPham sp1 = new SanPham(sp.getId(), sp.getMaSP(), sp.getTenSP(), sp.getTrangThai());
                new viewSPCT(sp1).setVisible(true);
            }
        });
    }

    private void fillTable(List<SanPhamChiTiet> l) {
        dtm = (DefaultTableModel) tblspct.getModel();
        dtm.setRowCount(0);
        for (SanPhamChiTiet x : l) {
            dtm.addRow(new Object[]{
                x.getId(), lblmasp.getText(), lbltensp.getText(), pls.findPL(x.getIdpl()).getTen(), cls.findCL(x.getIdcl()).getTen(), ths.findTH(x.getIdth()).getTen(), mss.findMS(x.getIdms()).getTen(),
                xxs.findXX(x.getIdxx()).getTen(), x.getKichThuoc(), x.getKhoiLuong(), x.getSoLuong(), x.getGia(), x.getMoTa(), x.getAnh()
            });
        }
    }

    private void LoadCBO() {
        cbochatlieu.removeAllItems();
        cbomausac.removeAllItems();
        cbophanloai.removeAllItems();
        cbothuonghieu.removeAllItems();
        cboxuatxu.removeAllItems();
        cbochatlieu1.removeAllItems();
        cbomausac1.removeAllItems();
        cbophanloai1.removeAllItems();
        cbothuonghieu1.removeAllItems();
        cboxuatxu1.removeAllItems();

        cbochatlieu1.addItem("Tất cả");
        cbomausac1.addItem("Tất cả");
        cbophanloai1.addItem("Tất cả");
        cbothuonghieu1.addItem("Tất cả");
        cboxuatxu1.addItem("Tất cả");
        for (ChatLieu x : cls.gettAll()) {
            cbochatlieu.addItem(x.getTen());
            cbochatlieu1.addItem(x.getTen());
        }
        for (PhanLoai x : pls.gettAll()) {
            cbophanloai.addItem(x.getTen());
            cbophanloai1.addItem(x.getTen());
        }
        for (MauSac x : mss.gettAll()) {
            cbomausac.addItem(x.getTen());
            cbomausac1.addItem(x.getTen());
        }
        for (ThuongHieu x : ths.gettAll()) {
            cbothuonghieu.addItem(x.getTen());
            cbothuonghieu1.addItem(x.getTen());
        }
        for (XuatXu x : xxs.gettAll()) {
            cboxuatxu.addItem(x.getTen());
            cboxuatxu1.addItem(x.getTen());
        }
    }

    private void Show(int i) {
        txtid.setText(tblspct.getValueAt(i, 0).toString());
        lblmasp.setText(tblspct.getValueAt(i, 1).toString());
        lbltensp.setText(tblspct.getValueAt(i, 2).toString());
        
        cbophanloai.setSelectedItem(tblspct.getValueAt(i, 3).toString());
        cbochatlieu.setSelectedItem(tblspct.getValueAt(i, 4).toString());
        cbothuonghieu.setSelectedItem(tblspct.getValueAt(i, 5).toString());
        cbomausac.setSelectedItem(tblspct.getValueAt(i, 6).toString());
        cboxuatxu.setSelectedItem(tblspct.getValueAt(i, 7).toString());
        txtkichthuoc.setText(tblspct.getValueAt(i, 8).toString());
        txtkhoiluong.setText(tblspct.getValueAt(i, 9).toString());
        txtsoluong.setText(tblspct.getValueAt(i, 10).toString());
        txtgia.setText(tblspct.getValueAt(i, 11).toString());
        txtamota.setText(tblspct.getValueAt(i, 12).toString());
    }

    public SanPhamChiTiet readFormSPCT() {
        SanPhamChiTiet spct = new SanPhamChiTiet();
        spct.setId(txtid.getText());
        spct.setIdsp(abc.getText());
        spct.setIdpl(pls.findidPL(cbophanloai.getSelectedItem().toString()).getId());
        spct.setIdms(mss.findidMS(cbomausac.getSelectedItem().toString()).getId());
        spct.setIdcl(cls.findidCL(cbochatlieu.getSelectedItem().toString()).getId());
        spct.setIdth(ths.findidTH(cbothuonghieu.getSelectedItem().toString()).getId());
        spct.setIdxx(xxs.findidXX(cboxuatxu.getSelectedItem().toString()).getId());
        spct.setKichThuoc(txtkichthuoc.getText());
        spct.setKhoiLuong(Float.parseFloat(txtkhoiluong.getText()));
        spct.setSoLuong(Integer.parseInt(txtsoluong.getText()));
        spct.setGia(Float.parseFloat(txtgia.getText()));
        spct.setMoTa(txtamota.getText());
        return spct;
    }

    public void Clear() {
        txtid.setText("");
        txtamota.setText("");
        txtgia.setText("");
        txtsoluong.setText("");
        txtkhoiluong.setText("");
        txtkichthuoc.setText("");
        cbochatlieu.setSelectedIndex(0);
        cbomausac.setSelectedIndex(0);
        cbophanloai.setSelectedIndex(0);
        cbothuonghieu.setSelectedIndex(0);
        cboxuatxu.setSelectedIndex(0);
    }

    public boolean Check() {
        Boolean c = true;

        try {
            Integer.parseInt(txtsoluong.getText());
            c = true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số nguyên");
            c = false;
        }
        try {
            Double.parseDouble(txtkhoiluong.getText());
            c = true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Khối lượng phải là số");
            c = false;
        }
        try {
            Double.parseDouble(txtgia.getText());
            c = true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá tiền phải là số");
            c = false;
        }
        if (txtkhoiluong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Khối lượng không trống");
            c = false;
        } else {
            if (Float.parseFloat(txtkhoiluong.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "Khối lượng phải lớn hơn 0");
                c = false;
            }
        }
        if (txtkichthuoc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kích thước không trống");
            c = false;
        }
        if (txtsoluong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số lượng không trống");
            c = false;
        } else {
            if (Integer.parseInt(txtsoluong.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0");
                c = false;
            }
        }
        if (txtgia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Giá tiền không trống");
            c = false;
        } else {
            if (Integer.parseInt(txtsoluong.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "Giá tiền phải lớn hơn 0");
                c = false;
            }
        }
        for (SanPhamChiTiet x : service.gettAll()) {
            if (x.getGia().equals(readFormSPCT().getGia()) && x.getIdcl().equals(readFormSPCT().getIdcl()) && x.getIdms().equals(readFormSPCT().getIdms())
                    && x.getIdpl().equals(readFormSPCT().getIdpl()) && x.getIdth().equals(readFormSPCT().getIdth()) && x.getIdxx().equals(readFormSPCT().getIdxx()) && x.getKhoiLuong().equals(readFormSPCT().getKhoiLuong())
                    && x.getKichThuoc().equals(readFormSPCT().getKichThuoc())) {
                JOptionPane.showMessageDialog(this, "Đã tồn tại sản phẩm như vậy không thể thêm");
                c = false;
            }
        }
        return c;
    }

    public boolean CheckT() {
        Boolean c = true;

        try {
            Integer.parseInt(txtsoluong.getText());
            c = true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số nguyên");
            c = false;
        }
        try {
            Double.parseDouble(txtkhoiluong.getText());
            c = true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là số");
            c = false;
        }
        try {
            Double.parseDouble(txtgia.getText());
            c = true;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Giá tiền phải là số");
            c = false;
        }
        if (txtkhoiluong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Khối lượng không trống");
            c = false;
        } else {
            if (Float.parseFloat(txtkhoiluong.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "Khối lượng phải lớn hơn 0");
                c = false;
            }
        }
        if (txtkichthuoc.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kích thước không trống");
            c = false;
        }
        if (txtsoluong.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Số lượng không trống");
            c = false;
        } else {
            if (Integer.parseInt(txtsoluong.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0");
                c = false;
            }
        }
        if (txtgia.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Giá tiền không trống");
            c = false;
        } else {
            if (Integer.parseInt(txtsoluong.getText()) <= 0) {
                JOptionPane.showMessageDialog(this, "Giá tiền phải lớn hơn 0");
                c = false;
            }
        }
        for (SanPhamChiTiet x : service.gettAll()) {
            int i = 0;
            if (x.getGia().equals(readFormSPCT().getGia()) && x.getIdcl().equals(readFormSPCT().getIdcl()) && x.getIdms().equals(readFormSPCT().getIdms())
                    && x.getIdpl().equals(readFormSPCT().getIdpl()) && x.getIdth().equals(readFormSPCT().getIdth()) && x.getIdxx().equals(readFormSPCT().getIdxx()) && x.getKhoiLuong().equals(readFormSPCT().getKhoiLuong())
                    && x.getKichThuoc().equals(readFormSPCT().getKichThuoc())) {
                i++;
                
            }if(i>0){
                JOptionPane.showMessageDialog(this, "Đã tồn tại sản phẩm như vậy không thể thêm");
                c = false;
            }
        }
        return c;
    }

    private void TimKiemSP() {
        String masp = txttimma.getText();
        String gia1 = "";
        String gia2 = "";
        if (cbogia.getSelectedItem().equals("Thấp hơn 100k")) {
            gia1 = "0";
            gia2 = "100000";
        } else if (cbogia.getSelectedItem().equals("100k - 200k")) {
            gia1 = "100000";
            gia2 = "200000";
        } else if (cbogia.getSelectedItem().equals("200k - 500k")) {
            gia1 = "200000";
            gia2 = "500000";
        } else if (cbogia.getSelectedItem().equals("Lớn hơn 500k")) {
            gia1 = "500000";
            gia2 = "9999999999999999999999999999999";
        } else {
            gia1 = "0";
            gia2 = "9999999999999999999999999999999";
        }
        String soluong = "";
        String khoiluong = "";
        String kichthuoc = "";
        String phanloai = "";
        String thuonghieu = "";
        String mausac = "";
        String xuatxu = "";
        String chatlieu = "";
        if (((String) cbomausac1.getSelectedItem()) == null || (cbomausac1.getSelectedIndex() == 0)) {
            mausac = "";
        } else {
            mausac = mss.findidMS((String) cbomausac1.getSelectedItem()).getId();
        }

        if (((String) cbochatlieu1.getSelectedItem()) == null || (cbochatlieu1.getSelectedIndex() == 0)) {
            chatlieu = "";
        } else {
            chatlieu = cls.findidCL((String) cbochatlieu1.getSelectedItem()).getId();
        }

        if (((String) cboxuatxu1.getSelectedItem()) == null || (cboxuatxu1.getSelectedIndex() == 0)) {
            xuatxu = "";
        } else {
            xuatxu = xxs.findidXX((String) cboxuatxu1.getSelectedItem()).getId();
        }

        if (((String) cbothuonghieu1.getSelectedItem()) == null || (cbothuonghieu1.getSelectedIndex() == 0)) {
            thuonghieu = "";
        } else {
            thuonghieu = ths.findidTH((String) cbothuonghieu1.getSelectedItem()).getId();
        }

        if (((String) cbophanloai1.getSelectedItem()) == null || (cbophanloai1.getSelectedIndex() == 0)) {
            phanloai = "";
        } else {
            phanloai = pls.findidPL((String) cbophanloai1.getSelectedItem()).getId();
        }

        dtm = (DefaultTableModel) tblspct.getModel();
        dtm.setRowCount(0);
        for (SanPham_SPCT x : service.TimSPCT(masp, masp, soluong, khoiluong, kichthuoc, phanloai,
                thuonghieu, mausac, xuatxu, chatlieu, gia1, gia2)) {
            dtm.addRow(new Object[]{
                x.getIdspct(), x.getMaSP(), x.getTenSP(), pls.findPL(x.getIdPL()).getTen(), cls.findCL(x.getIdCL()).getTen(), ths.findTH(x.getIdTH()).getTen(),
                mss.findMS(x.getIdMS()).getTen(),
                xxs.findXX(x.getIdXX()).getTen(), x.getKichThuoc(), x.getKhoiLuong(), x.getSoLuong(), x.getGia()
            });
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abc;
    private javax.swing.JButton btnmoi;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btnthem;
    private javax.swing.JButton btnthemcl;
    private javax.swing.JButton btnthemphanloai;
    private javax.swing.JButton btnthemth;
    private javax.swing.JButton btnthemxx;
    private javax.swing.JButton btnxemct;
    private javax.swing.JButton btnxoa;
    private javax.swing.JComboBox<String> cbochatlieu;
    private javax.swing.JComboBox<String> cbochatlieu1;
    private javax.swing.JComboBox<String> cbogia;
    private javax.swing.JComboBox<String> cbomausac;
    private javax.swing.JComboBox<String> cbomausac1;
    private javax.swing.JComboBox<String> cbophanloai;
    private javax.swing.JComboBox<String> cbophanloai1;
    private javax.swing.JComboBox<String> cbothuonghieu;
    private javax.swing.JComboBox<String> cbothuonghieu1;
    private javax.swing.JComboBox<String> cboxuatxu;
    private javax.swing.JComboBox<String> cboxuatxu1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblmasp;
    private javax.swing.JLabel lblspanh;
    private javax.swing.JLabel lbltensp;
    private javax.swing.JTable tblspct;
    private javax.swing.JButton tbmthemms;
    private javax.swing.JTextArea txtamota;
    private javax.swing.JTextField txtgia;
    private javax.swing.JLabel txtid;
    private javax.swing.JTextField txtkhoiluong;
    private javax.swing.JTextField txtkichthuoc;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttimma;
    // End of variables declaration//GEN-END:variables
}
